title: "[Idea] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      placeholder: Tell us the pain this fixes…
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Your proposal
      placeholder: What should Ad Mute do?
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Nice to have
        - Important
        - Top priority
